version: 0.0
os: linux
files:
  - source: target/VendorAPICall-1.0.0.jar
    destination: /home/ec2-user/javaapp
hooks:
  AfterInstall:
    - location: scripts/start_app
      timeout: 300
      runas: root
