version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  type: zip 
  files: 
    - 'appspec.yml'
    - 'scripts/start_server'
    - 'scripts/install_dependencies'  
    - 'target/VendorAPICall-1.0.0.jar'
